### ISSUE TITLE
Update the template schema to get version automatically

### ISSUE THREAD

**Issue by thoth291** [ericmjl/minimal-flask-example#1]
https://github.com/ericmjl/minimal-flask-example/blob/43ab49e15dacfb81a62ed33efdff97e76f9fdf62/templates/data.html#L4

Thank you for this example!
I would suggest to update the template with bokeh version variable and then supply it from python using return of `bokeh.__version__` - this should make your example bokeh_version agnostic.

**Comment by ericmjl** [comment]
@thoth291 thanks for letting me know! That's a good idea, I'll update the example accordingly.

**Comment by ericmjl** [comment]
Updated, therefore closing.
